VIA_ENABLE = no

CONSOLE_ENABLE ?= no
KEYCODE_STRING_ENABLE ?= no

COMMAND_ENABLE = no
MOUSEKEY_ENABLE = yes
SPACE_CADET_ENABLE = no
CAPS_WORD_ENABLE = yes
COMBO_ENABLE = no
DYNAMIC_TAPPING_TERM_ENABLE = no
KEY_OVERRIDE_ENABLE = no
LEADER_ENABLE = no
LAYER_LOCK_ENABLE = yes
REPEAT_KEY_ENABLE = no
LTO_ENABLE = yes
EXTRAKEY_ENABLE = yes
TAP_DANCE_ENABLE = no

NKRO_ENABLE = no
GRAVE_ESC_ENABLE = no
AUDIO_ENABLE = no

UNICODE_ENABLE = no
UNICODEMAP_ENABLE = no
UCIS_ENABLE = no
UNICODE_COMMON = no
OS_DETECTION_ENABLE = yes

RGB_MATRIX_ENABLE = no
